version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: enhance_resume_app
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
  db:
    image: postgres:15
    container_name: enhance_resume_postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5440:5432
