"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv


# Load env file from project directory
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-c5nvx+&pyo^uhbi7!jd+t1s5i@q_r595i%e)2v^1xb@in3w832"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "https://resustackapp.com,https://www.resustackapp.com"
).split(",")

if not DEBUG:
    # Tell Django to trust the X-Forwarded-Proto header that comes from the proxy
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Force SSL redirect
    SECURE_SSL_REDIRECT = True

    # Mark cookies as secure
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "resume",
    "crispy_forms",
    "crispy_bootstrap4",
    "rest_framework",
    "rest_framework.authtoken",
    "mcp_server",
    # Sign in with Google. Only allauth's social side is used; sign-in, sign-up
    # and passwords stay on ResuStack's own views.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

# The API is reached two ways: the site's own session, and a token the user
# issues for an MCP client. Session first, so browser calls keep working.
REST_FRAMEWORK = {
    # Token first so an unauthenticated API call answers 401 with a challenge
    # rather than 403; session auth still applies whenever a cookie is present.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.CanonicalHostMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "core.middleware.GoogleLoginAvailabilityMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "resume.context_processors.ui_translations",
                "core.context_processors.account_status",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


# Construct Database Configuration from Environment Variables
DB_NAME = os.environ.get("POSTGRES_DB", "postgres")
DB_USER = os.environ.get("POSTGRES_USER", "postgres")
DB_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "postgres")
DB_HOST = os.environ.get("POSTGRES_HOST", "db")
DB_PORT = os.environ.get("POSTGRES_PORT", "5432")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "sslmode": "disable",  # Explicitly disable SSL for Docker internal network
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media Files (Uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
LOGIN_URL = "/accounts/login/"  # Custom login page
LOGIN_REDIRECT_URL = "/dashboard/"  # Redirect to dashboard after login
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Redirect to login after logout

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# --- Sign in with Google (django-allauth) -------------------------------------
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
# The Google button only appears once both credentials are configured.
GOOGLE_LOGIN_ENABLED = bool(GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET)

ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
# allauth sends no verification mail. Email sign-ups use ResuStack's own soft
# verification (core/email_verification.py); Google sign-ups arrive with an
# address Google verified, or are refused (core/adapters.py).
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True

# Never sign someone in to, or attach Google to, an existing account because the
# email matches. Addresses on local accounts were never verified, so matching on
# them would let whoever registered an address first take over the real owner's
# account. Linking happens only from the Profile page, while signed in.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False
# Always stop at the sign-up step: it carries the consent to transfers abroad.
SOCIALACCOUNT_AUTO_SIGNUP = False
# Starting a sign-in takes a POST, so a link cannot start one on someone's behalf.
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = "core.adapters.SocialAccountAdapter"
SOCIALACCOUNT_FORMS = {"signup": "core.forms.GoogleSignupForm"}
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "OAUTH_PKCE_ENABLED": True,
        "FETCH_USERINFO": False,
        **(
            {
                "APP": {
                    "client_id": GOOGLE_OAUTH_CLIENT_ID,
                    "secret": GOOGLE_OAUTH_CLIENT_SECRET,
                    "key": "",
                }
            }
            if GOOGLE_LOGIN_ENABLED
            else {}
        ),
    }
}

# How long the link in a verification email stays valid, in seconds.
EMAIL_VERIFICATION_MAX_AGE = 3 * 24 * 60 * 60

# Email Configuration
# For development: emails are printed to console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'ResuStack <noreply@resustack.com>'

# For production with SMTP (uncomment and configure):
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Defaults are Gmail with an app password. Switching provider is a matter of
# environment variables — e.g. Cloudflare Email Service needs
# EMAIL_HOST=smtp.mx.cloudflare.net, EMAIL_PORT=465, EMAIL_USE_TLS=False,
# EMAIL_USE_SSL=True. TLS (STARTTLS) and SSL (implicit TLS) are exclusive.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").strip().lower() in ("1", "true", "yes")
EMAIL_USE_TLS = (
    not EMAIL_USE_SSL
    and os.environ.get("EMAIL_USE_TLS", "True").strip().lower() in ("1", "true", "yes")
)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER or "webmaster@localhost"


# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "resume.services": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "weasyprint": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "fontTools": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # The TypeSafe SDK logs request and response bodies at DEBUG — resume
        # text and job postings. Pinned above that so a stray
        # TYPESAFE_LOG_LEVEL=debug cannot put user content in the logs.
        "typesafe_sdk": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

# TypeSafe (Jev) answers the typed judgments — match scoring, import checks,
# tool-call guardrails. Text generation stays with OpenAI. The model is pinned
# to an exact release so stored scores do not drift when `jev-latest` moves;
# bump it deliberately, after `manage.py jev_eval`.
TYPESAFE_API_KEY = os.environ.get("TYPESAFE_API_KEY", "")
# The test runner loads the same .env; without this a test that forgot to mock
# Jev would quietly call the real API. Tests that need a key override it.
if len(sys.argv) > 1 and sys.argv[1] == "test":
    TYPESAFE_API_KEY = ""
TYPESAFE_MODEL = os.environ.get("TYPESAFE_MODEL", "jev-1.13.0")
TYPESAFE_TIMEOUT = float(os.environ.get("TYPESAFE_TIMEOUT", "15"))

# TODO: Convert to template selector map (faangpath-simple: faangpath_simple_template.tex, cls)
# LATEX_SETTINGS = {
#     'TEMPLATE_DIR': BASE_DIR / 'latex_renderer' / 'templates',
#     'TEMP_DIR': BASE_DIR / 'latex_renderer' / 'templates' / 'temp_latex_files',
#     'DEFAULT_TEMPLATE': 'faangpath_simple_template.tex',
#     'PDF_TIMEOUT': 30,
# }

# TEMPLATE_SELECTOR_PREVIEW_MAP = {
#     'faangpath-simple': 'faangpath_simple_template_preview.html'
# }

# Map LaTeX templates to HTML preview templates (Phase 4)
# TEX_PREVIEW_HTML_MAP = {
#     'faangpath_simple_template.tex': 'faangpath_simple_template_preview.html'
# }


# Derived from the design catalogue so a template added there is immediately
# renderable, selectable in the editor and listed over MCP.
from resume.resume_templates import selector_html_map  # noqa: E402

TEMPLATE_SELECTOR_HTML_MAP = selector_html_map()

# PDF Generation Settings
PDF_SETTINGS = {
    "ENGINE": "weasyprint",
    "ENABLE_LOGGING": True,
    "FONT_CONFIG": True,
}

# How long a signed PDF download link stays usable. It is single-use as well,
# so this only bounds how long a leaked link is worth anything.
DOWNLOAD_LINK_MAX_AGE = int(os.environ.get("DOWNLOAD_LINK_MAX_AGE", "600"))

# The proof record served at /.well-known/mcp-registry-auth, e.g.
# "v=MCPv1; k=ed25519; p=<base64 public key>". A public key only; the private
# key stays with whoever runs `mcp-publisher login http`.
MCP_REGISTRY_AUTH = os.environ.get("MCP_REGISTRY_AUTH", "")

# The version of the privacy policy a new user consents to at sign-up — the
# "Last updated" date on /privacy/ and /gizlilik/. Change it together with the
# policy text, so each stored consent points at the words it agreed to.
PRIVACY_POLICY_VERSION = "2026-09-19"

# Restore points kept per resume, for every plan. Each is a full copy of the
# content (a few KB), so a bound keeps the table from growing with every edit.
REVISION_HISTORY_LIMIT = 10

# Subscription Tier Limits
FREE_TIER_LIMITS = {
    "import_count": 2,  # Monthly PDF imports
    "enhance_count": 10,  # Monthly AI enhancements (experience + project combined)
    "download_count": 5,  # Monthly PDF downloads
    "resume_count": 3,  # Total resume count (not monthly)
    "agent_message_count": 10,  # Monthly agent chat messages
}

# Purchasable access. One-time periods, not subscriptions — see
# resume/services/payment_service.py for why.
PREMIUM_PLANS = [
    {
        "code": "pro_3m",
        "name": "Pro · 3 months",
        "days": 90,
        "price_display": "$9",
        "blurb": "Covers a typical job search.",
        "checkout_url": os.environ.get("CHECKOUT_URL_PRO_3M", ""),
        "provider_product_id": os.environ.get("PRODUCT_ID_PRO_3M", ""),
        "highlight": True,
    },
    {
        "code": "pro_12m",
        "name": "Pro · 12 months",
        "days": 365,
        "price_display": "$24",
        "blurb": "For a longer search, or coming back for the next one.",
        "checkout_url": os.environ.get("CHECKOUT_URL_PRO_12M", ""),
        "provider_product_id": os.environ.get("PRODUCT_ID_PRO_12M", ""),
        "highlight": False,
    },
]

PAYMENTS = {
    # "coming_soon" until a provider is chosen: the plans are shown so people
    # know what Pro will cost, but nothing tries to take money. Flip to "live"
    # once checkout URLs and a webhook secret are configured.
    "STATUS": os.environ.get("PAYMENT_STATUS", "coming_soon"),
    "PROVIDER": os.environ.get("PAYMENT_PROVIDER", "lemonsqueezy"),
    "WEBHOOK_SECRET": os.environ.get("PAYMENT_WEBHOOK_SECRET", ""),
}

# Agent Chat Rate Limiting
AGENT_CHAT_RATE_LIMIT = {
    "max_requests": 20,  # Maximum requests per window
    "window_seconds": 60,  # Time window in seconds
}

# Cache backend.
#
# Must be shared across processes: gunicorn runs several workers, and both the
# agent's pending-approval state and the chat rate limit are meaningless if
# each worker keeps its own copy — an approval parked by one worker looks
# expired to the next. LocMemCache is per-process, so it is only used when
# running a single-process dev server without a database cache table.
CACHES = {
    "default": {
        "BACKEND": os.environ.get(
            "CACHE_BACKEND", "django.core.cache.backends.db.DatabaseCache"
        ),
        "LOCATION": os.environ.get("CACHE_LOCATION", "resustack_cache"),
    }
}
