from django.conf import settings

import openai
from openai import OpenAI

client = OpenAI(api_key=settings.OPENAI_API_KEY)


def send_openai_message(user_message:str, meta_prompt:str = None):
    """
    Sends a message to the OpenAI API with a specified system prompt.

    Parameters:
        user_message (str): The content provided by the user to be processed.
        meta_prompt (str): The system prompt to guide the assistant's response style.
                           Defaults to a generic "helpful assistant" if not specified.

    Returns:
        str: The response content generated by the OpenAI API, or an error message in case of an exception.
    """
    meta_prompt = meta_prompt if meta_prompt else "You are a helpful assistant."

    try:
        response = client.chat.completions.create(
            # model="gpt-4o-mini",
            # model="gpt-3.5-turbo",
            model="gpt-4o",
            messages=[
                {"role": "system", "content": meta_prompt},
                {"role": "user", "content": user_message}
            ]
        )

        return response.choices[0].message.content

    except openai.APIError as e:
        return f"OpenAI API returned an API Error: {e}"
    except openai.RateLimitError as e:
        return f"OpenAI API request exceeded rate limit: {e}"
    except Exception as e:
        return f"Error: {str(e)}"


# TODO Convert class based structure
def enhance_resume_experience(user_message:str):
    """
    Enhances work experience descriptions to be suitable for a resume in the STAR format.

    Parameters:
        user_message (str): The user's work experience description(s) to be improved.

    Returns:
        str: The STAR-enhanced, resume-ready work experience description(s).
    """

    meta_prompt = """
    Act as a professional resume experience enhancer.
    
    I will provide work experience descriptions. Your task:
    
    1. SPLIT into separate bullet points:
       - If the input contains multiple distinct achievements, responsibilities, or topics, 
         split them into separate lines (one achievement per line).
       - Each line should focus on ONE specific accomplishment or responsibility.
    
    2. ENHANCE each bullet point:
       - Start with a strong action verb (Developed, Implemented, Led, Optimized, etc.)
       - Follow the STAR format implicitly (Situation-Task-Action-Result)
       - Include metrics and quantifiable results when possible
       - Keep each bullet concise (ideally 1-2 lines)
    
    3. OUTPUT FORMAT:
       - Return each bullet point on a separate line
       - No bullet point symbols, just plain text
       - One empty line between each bullet point
       - No numbering
    
    Example Input:
    "Developed backend solutions using Django, collaborated with DevOps on Kubernetes, implemented WebSocket for notifications."
    
    Example Output:
    Developed efficient backend solutions using Django and Django Rest Framework, improving API response time by 40%

    Collaborated with DevOps team to optimize Kubernetes Helm configurations, reducing deployment time by 25%

    Implemented WebSocket integration for real-time notification and messaging services, enhancing user engagement
    """.strip()

    return send_openai_message(
        user_message=user_message, meta_prompt=meta_prompt
    )


def enhance_project_description(user_message:str):
    """
    Enhances project description to be suitable for a resume in the STAR format.

    Parameters:
        user_message (str): The user's project description to be improved.

    Returns:
        str: The STAR-enhanced, resume-ready project description.
    """

    meta_prompt = """
    Act as a professional project description enhancer for resumes.
    
    I will provide project descriptions. Your task:
    
    1. ANALYZE the content:
       - Identify distinct features, achievements, or technical implementations
       - If multiple topics exist, split them into separate statements
    
    2. ENHANCE each point:
       - Start with action verbs (Built, Developed, Designed, Implemented, etc.)
       - Highlight technologies used
       - Include quantifiable impact when possible (users, performance, scale)
       - Keep each point concise and impactful
    
    3. OUTPUT FORMAT:
       - For projects with multiple features: return each on a separate line
       - One empty line between points
       - No bullet points or numbering
       - Focus on technical achievements and measurable outcomes
    
    Example Input:
    "Built a tool to search for Hiring Managers using ReactJS and Firebase. Over 25000 people have used it."
    
    Example Output:
    Built a Hiring Manager search tool using ReactJS, NodeJS, and Firebase, serving over 25,000 users

    Implemented boolean query system that outperforms LinkedIn search results in relevance and accuracy
    """.strip()

    return send_openai_message(
        user_message=user_message, meta_prompt=meta_prompt
    )

def extract_resume_data(user_message: str):
    """
    Extracts structured resume data from a given text using OpenAI GPT.

    Parameters:
        user_message (str): The raw text extracted from a resume.

    Returns:
        str: A JSON string containing structured resume data.
    """

    meta_prompt = """
    Act as a resume parser. I will provide you with raw text extracted from a resume. 
    Your task is to extract and structure the data into the following JSON format:

    {
        "user_info": {
            "full_name": "extracted_full_name",
            "email": "extracted_email",
            "phone": "extracted_phone",
            "address": "extracted_address",
            "linkedin": "extracted_linkedin_url",
            "github": "extracted_github_url",
            "skills": ["extracted_skill1", "extracted_skill2"]
        },
        "experience": [
            {
                "title": "extracted_job_title1",
                "company": "extracted_company1",
                "start_date": "extracted_start_date1",
                "end_date": "extracted_end_date1",
                "description": ["bullet_point_1", "bullet_point_2", "bullet_point_3"],
                "current_role": "True/False if currently working in this role" but Boolean
            },
            {
                "title": "extracted_job_title2",
                "company": "extracted_company2",
                "start_date": "extracted_start_date2",
                "end_date": "extracted_end_date2",
                "current_role": "True/False if currently working in this role" but Boolean
            }
        ],
        "education": [
            {
                "degree": "extracted_degree1",
                "school": "extracted_school1",
                "field_of_study": "extracted_field_of_study1",
                "start_date": "extracted_start_date1",
                "end_date": "extracted_end_date1"
            },
            {
                "degree": "extracted_degree2",
                "school": "extracted_school2",
                "start_date": "extracted_start_date2",
                "end_date": "extracted_end_date2"
            }
        ],
        "projects_and_publications": [
            {
                "name": "extracted_project_or_publication_title1",
                "description": "extracted_project_or_publication_description1",
                "link": "extracted_link"
            },
            {
                "name": "extracted_project_or_publication_title2",
                "description": "extracted_project_or_publication_description2",
                "link": "extracted_link2"
            }
        ]
    }

    For the "experience" section:
    - Return "description" as a JSON array of strings, where each string is one achievement/responsibility bullet point.
    - Each bullet point should be a clear, action-oriented statement (e.g., "Developed a dashboard for real-time monitoring").
    - If the start and end dates are not explicitly mentioned for a task or project, inherit them from the main job entry.

    For "education" section:
    - degree should be Bachelor, Master, or PhD.
    - field of study should be Computer Science, Engineering, etc.
    
    The start and end dates should be in the format YYYY-MM

    For "projects_and_publications" section:
    - if link is not valid url, leave it empty.

    For "user_info" section:
    - if linkendin and github not valid url, leave it empty.
    - if there linkedin url or github url, urls should be start with https://
    
    Ensure the JSON is well-structured and includes all relevant information. 
    If a section is missing in the input text, leave it empty in the JSON.
    """

    return send_openai_message(
        user_message=user_message, meta_prompt=meta_prompt
    )

def extract_linkedin_resume_data(user_message: str):
    """
    Parses LinkedIn profile data from a PDF file using OpenAI's API.

    Args:
        file: The uploaded LinkedIn PDF file.

    Returns:
        str: Parsed data as a JSON string.
    """
    meta_prompt = """
    Act as a LinkedIn profile parser. I will provide you with raw text extracted from a LinkedIn profile.  
    Your task is to extract and structure the data into the following JSON format:

    {
    "user_info": {
        "full_name": "extracted_full_name",
        "email": "extracted_email",
        "phone": "extracted_phone",
        "address": "extracted_address",
        "linkedin": "extracted_linkedin_url",
        "github": "extracted_github_url",
        "skills": ["extracted_skill1", "extracted_skill2"]
    },
    "experience": [
        {
        "title": "job_title",
        "company": "company_name",
        "start_date": "YYYY-MM",
        "end_date": "YYYY-MM or null if current",
        "location": "city, country (if available)",
        "description": "full_description",
        "current_role": true/false
        }
    ],
    "education": [
        {
        "school": "university_name",
        "degree": "Bachelor / Master / PhD",
        "field_of_study": "field_name",
        "start_date": "YYYY-MM",
        "end_date": "YYYY-MM"
        }
    ]
    }

    Guidelines:
    - Dates must be in YYYY-MM format if months are available; otherwise just YYYY.
    - Extract skills and certifications from any relevant sections or lists.
    - For `current_role`, mark as `true` if the person is still working in that position.
    - If any field is missing in the input, set it to null or leave it empty.
    - Remove page numbers or artifacts (e.g., “Page 1 of 3”) from descriptions.
    - In descriptions, use newlines as element, no bullet.
    - If there is only YYYY, use 01 as MM and result should be YYYY-01.
    - If there linkedin url or github url, urls should be start with https://

    Ensure the JSON output is well-formed, accurate, and complete.
    """

    return send_openai_message(
        user_message=user_message, meta_prompt=meta_prompt
    )