# Generated by Django 4.2.16 on 2026-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_create_userprofiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_selector',
            field=models.CharField(default='faangpath-simple', max_length=50),
        ),
    ]
