# Generated by Django 4.2.16 on 2026-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_userprofile_ui_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
