# Generated by Django 4.2.16 on 2026-09-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_ui_mode_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('template_selector', models.CharField(default='faangpath-simple', max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual edit'), ('agent', 'Agent'), ('import', 'Import'), ('revert', 'Revert')], default='manual', max_length=20)),
                ('tool_name', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='resume.resume')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['resume', '-created_at'], name='resume_resu_resume__cfdc8b_idx')],
            },
        ),
    ]
