# Generated by Django 4.2.16 on 2026-09-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_resumerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='resume',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resume.resume'),
        ),
    ]
