# Generated by Django 4.2.16 on 2026-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_destructive',
            field=models.BooleanField(default=True),
        ),
    ]
