# Generated by Django 4.2.16 on 2026-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_application_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumerevision',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual edit'), ('agent', 'Agent'), ('import', 'Import'), ('revert', 'Revert'), ('mcp', 'MCP client')], default='manual', max_length=20),
        ),
    ]
