# Generated by Django 4.2.16 on 2026-09-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_alter_resumerevision_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_consent_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
