# Generated by Django 4.2.16 on 2026-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_privacy_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_required',
            field=models.BooleanField(default=False),
        ),
    ]
