# Generated by Django 4.2.16 on 2026-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_email_verification_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='import_review',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
