# Generated by Django 4.2.16 on 2026-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_resume_import_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='scoring_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
