# Generated by Django 4.2.16 on 2026-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_jobposting_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applied_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
