# Generated by Django 4.2.16 on 2026-09-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_jobposting_tracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
