# Generated by Django 4.2.16 on 2026-09-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0026_delete_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='derived_kind',
            field=models.CharField(blank=True, choices=[('translation', 'Language version'), ('job', 'Job branch')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumerevision',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual edit'), ('agent', 'Agent'), ('import', 'Import'), ('revert', 'Revert'), ('mcp', 'MCP client'), ('branch', 'From a job branch')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('scorer', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='resume.jobposting')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='resume.resume')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='resume.jobposting'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint'), name='one_posting_per_text'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['resume', 'posting', '-created_at'], name='resume_eval_resume__805240_idx'),
        ),
    ]
